name: Test, Build and Deploy

on:
  push:
    branches: [master, main]

jobs:
  test:
    runs-on: ubuntu-22.04
    env:
      # variables for our front-end tests, see client/src/config.ts
      VITE_API_ORIGIN: http://localhost:3000
      VITE_API_PATH: /api/v1/trpc
      VITE_AUTH0_TEST_EMAIL: ${{ secrets.AUTH0_TEST_EMAIL }}
      VITE_AUTH0_TEST_PASSWORD: ${{ secrets.AUTH0_TEST_PASSWORD }}
      VITE_AUTH0_DOMAIN: ${{ secrets.AUTH0_DOMAIN }}
      VITE_AUTH0_CLIENT_ID: ${{ secrets.CLIENT_AUTH0_CLIENT_ID }}
      VITE_AUTH0_AUDIENCE: ${{ secrets.AUTH0_AUDIENCE}}
      VITE_AUTH0_CALLBACK_URL: ${{ secrets.AUTH0_CALLBACK_URL }}

      # variables for our back-end tests, see server/src/config.ts
      TEST_DATABASE_URL: postgres://capstone:capstone@localhost:5433/testdb
      DATABASE_URL: postgres://capstone:capstone@localhost:5434/devdb
      BASE_URL: http://localhost:3000

      SMTP_HOST: ${{ secrets.SMTP_HOST }}
      SMTP_PORT: ${{ secrets.SMTP_PORT }}
      SMTP_USER: ${{ secrets.SMTP_USER }}
      SMTP_PASS: ${{ secrets.SMTP_PASS }}

      AUTH0_AUDIENCE: ${{ secrets.AUTH0_AUDIENCE }}
      AUTH0_DOMAIN: ${{ secrets.AUTH0_DOMAIN }}
      CLIENT_ORIGIN_URL: ${{ secrets.CLIENT_ORIGIN_URL }}
      AUTH0_CLIENT_ID: ${{ secrets.SERVER_AUTH0_CLIENT_ID }}
      AUTH0_CLIENT_SECRET: ${{ secrets.SERVER_AUTH0_CLIENT_SECRET }}
    services:
      postgres-test:
        image: postgres:16.1-alpine
        env:
          POSTGRES_USER: capstone
          POSTGRES_PASSWORD: capstone
          POSTGRES_DB: testdb
        ports:
          - 5433:5432
      postgres-dev:
        image: postgres:16.1-alpine
        env:
          POSTGRES_USER: capstone
          POSTGRES_PASSWORD: capstone
          POSTGRES_DB: devdb
        ports:
          - 5434:5432
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.14.0'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Wait for PostgreSQL test database to be ready
        run: |
          until pg_isready -h localhost -p 5433; do
            echo "Waiting for PostgreSQL Test DB..."
            sleep 5
          done

      - name: Wait for PostgreSQL dev database to be ready
        run: |
          until pg_isready -h localhost -p 5434; do
            echo "Waiting for PostgreSQL Dev DB..."
            sleep 5
          done

      - name: Type check server
        run: npm run typecheck -w=server

      - name: Format code server
        run: npm run format -w=server

      - name: Format code client
        run: npm run format -w=client

      - name: Type check client
        run: npm run typecheck -w=client

      - name: Lint server
        run: npm run lint -w=server

      - name: Lint client
        run: npm run lint -w=client

      - name: Test client (unit)
        run: npm run test:unit -w=client

      - name: Run server database migrations
        run: npm run migrate:latest -w=server

      - name: Test server
        run: npm run test -w=server

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps chromium

      - name: Start server for E2E tests
        run: npm run dev -w=server &

      - name: Build front end for E2E tests
        run: npm run build -w=client

      - name: Wait for server to startup
        uses: Jtalk/url-health-check-action@v4
        with:
          max-attempts: 5
          retry-delay: 5s
          url: ${{ env.VITE_API_ORIGIN }}/api/health

      - name: Test client E2E
        run: npm run test:e2e -w=client

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: client/playwright-report/
          retention-days: 7

  build-deploy:
    needs: test
    runs-on: ubuntu-22.04
    if: github.ref == 'refs/heads/main'
    env:
      CLIENT_IMAGE_TAG: client-${{ github.sha }}
      SERVER_IMAGE_TAG: server-${{ github.sha }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Setup aws lightsail cli
        run: |
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          sudo ./aws/install --bin-dir /usr/local/bin --install-dir /usr/local/aws-cli --update
          which aws
          aws --version
          sudo curl "https://s3.us-west-2.amazonaws.com/lightsailctl/latest/linux-amd64/lightsailctl" -o "/usr/local/bin/lightsailctl"
          sudo chmod +x /usr/local/bin/lightsailctl

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ vars.AWS_REGION }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Build server image
        run: >
          docker build
          -t $SERVER_IMAGE_TAG
          -f ./server/Dockerfile .

      - name: Build client image

        run: >
          docker build
          -t $CLIENT_IMAGE_TAG
          --build-arg VITE_AUTH0_DOMAIN=${{ secrets.AUTH0_DOMAIN }}
          --build-arg VITE_AUTH0_CLIENT_ID=${{ secrets.PROD_AUTH0_CLIENT_ID }}
          --build-arg VITE_AUTH0_AUDIENCE=${{ secrets.AUTH0_AUDIENCE }}
          --build-arg VITE_AUTH0_CALLBACK_URL=${{ secrets.PROD_AUTH0_CALLBACK_URL }}
          --build-arg VITE_AUTH0_TEST_EMAIL=${{ secrets.AUTH0_TEST_EMAIL }}
          --build-arg VITE_AUTH0_TEST_PASSWORD=${{ secrets.AUTH0_TEST_PASSWORD }}
          --build-arg VITE_API_PATH=${{ vars.API_PATH }}
          --build-arg VITE_API_SERVER_URL=${{ vars.API_SERVER_URL }}
          -f ./client/Dockerfile .

      - name: Push server image
        run: >-
          aws lightsail push-container-image
          --service-name ${{ vars.AWS_LIGHTSAIL_SERVICE }}
          --label ${{ env.SERVER_IMAGE_TAG }}
          --image ${{ env.SERVER_IMAGE_TAG }}
          --output yaml

      - name: Push client image
        run: >-
          aws lightsail push-container-image
          --service-name ${{ vars.AWS_LIGHTSAIL_SERVICE }}
          --label ${{ env.CLIENT_IMAGE_TAG }}
          --image ${{ env.CLIENT_IMAGE_TAG }}
          --output yaml

      - name: Get Lightsail image tag
        run: |
          aws lightsail get-container-images --service-name ${{ vars.AWS_LIGHTSAIL_SERVICE }} | jq -r '.containerImages[] | select(.image | contains(".'$SERVER_IMAGE_TAG'")) | .image'
          echo "LIGHTSAIL_SERVER_IMAGE=$(aws lightsail get-container-images --service-name ${{ vars.AWS_LIGHTSAIL_SERVICE }} | jq -r '.containerImages[] | select(.image | contains(".'$SERVER_IMAGE_TAG'")) | .image')" >> $GITHUB_ENV
          echo "LIGHTSAIL_CLIENT_IMAGE=$(aws lightsail get-container-images --service-name ${{ vars.AWS_LIGHTSAIL_SERVICE }} | jq -r '.containerImages[] | select(.image | contains(".'$CLIENT_IMAGE_TAG'")) | .image')" >> $GITHUB_ENV

      - name: Create containers.json
        run: |
          echo '{
            "client": {
              "image": "${{ env.LIGHTSAIL_CLIENT_IMAGE }}",
              "command": [],
              "ports": {
                "80": "HTTP"
              },
              "environment": {
                "API_PROXY_PASS": "http://localhost:3000"
              }
            },
            "server": {
              "image": "${{ env.LIGHTSAIL_SERVER_IMAGE }}",
              "ports": {
                "3000": "HTTP"
              },
              "environment": {
                "NODE_ENV": "production",
                "PORT": "3000",
                "DATABASE_URL": "${{ secrets.PROD_DATABASE_URL }}",
                "TEST_DATABASE_URL": "${{ secrets.PROD_DATABASE_URL }}",
                "TOKEN_KEY": "${{ secrets.PROD_TOKEN_KEY }}",
                "AUTH0_DOMAIN": "${{ secrets.AUTH0_DOMAIN }}",
                "AUTH0_CLIENT_ID": "${{ secrets.SERVER_AUTH0_CLIENT_ID }}",
                "AUTH0_CLIENT_SECRET": "${{ secrets.SERVER_AUTH0_CLIENT_SECRET }}",
                "AUTH0_AUDIENCE": "${{ secrets.AUTH0_AUDIENCE }}",
                "CLIENT_ORIGIN_URL": "${{ secrets.PROD_CLIENT_ORIGIN_URL }}",
                "SMTP_HOST": "${{ secrets.SMTP_HOST }}",
                "SMTP_PORT": "${{ secrets.SMTP_PORT }}",
                "SMTP_USER": "${{ secrets.SMTP_USER }}",
                "SMTP_PASS": "${{ secrets.SMTP_PASS }}"
              }
            }
          }' > containers.json

      - name: Create public-endpoint.json file
        run: |
          echo '{
            "containerName": "client",
            "containerPort": 80,
            "healthCheck": {
              "intervalSeconds": 15,
              "path": "/api/health"
            }
          }' > public-endpoint.json

      - name: Deploy to AWS Lightsail
        run: |
          aws lightsail create-container-service-deployment \
          --service-name ${{ vars.AWS_LIGHTSAIL_SERVICE }} \
          --containers file://containers.json \
          --public-endpoint file://public-endpoint.json
